import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import "./globals.css";
import { HeaderWrapper } from "@/component/common/header/HeaderWrapper";
import { Footer } from "@/component/common/footer/Footer";

const notoJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoJP.className}  antialiased flex flex-col min-h-screen`}
      >
        <HeaderWrapper />
        <section className="pt-[var(--header-height)] flex-1 ">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
